refactor: update cli tmux scripts

diff --git a/cli/dot b/cli/dot
--- a/cli/dot
+++ b/cli/dot
@@ -27,6 +27,7 @@ dot_usage() {
   # :command.usage_commands
   printf "%s\n" "Commands:"
   printf "  %s   \n" "waybar"
+  printf "  %s   \n" "tmux  "
   echo
 
   # :command.long_usage
@@ -101,6 +102,77 @@ dot_waybar_watch_usage() {
   printf "%s\n" "Usage:"
   printf "  dot waybar watch\n"
   printf "  dot waybar watch --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+dot_tmux_usage() {
+  printf "dot tmux\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  dot tmux COMMAND\n"
+  printf "  dot tmux [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "Commands:"
+  printf "  %s   open project\n" "project"
+  printf "  %s   create a tmux session\n" "create "
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+dot_tmux_project_usage() {
+  printf "dot tmux project - open project\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  dot tmux project\n"
+  printf "  dot tmux project --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+dot_tmux_create_usage() {
+  printf "dot tmux create - create a tmux session\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  dot tmux create\n"
+  printf "  dot tmux create --help | -h\n"
   echo
 
   # :command.long_usage
@@ -203,6 +275,74 @@ dot_waybar_watch_command() {
 
 }
 
+# :command.function
+dot_tmux_project_command() {
+
+  # src/tmux_project_command.sh
+  #!/bin/bash
+
+  PROJECTS_DIR="$HOME/git"
+  SCRIPTS_DIR="$(dirname "$0")"
+
+  selected=$(
+          find "$PROJECTS_DIR" -mindepth 3 -maxdepth 3 -type d \
+          | sed "s|^$PROJECTS_DIR/||" \
+          | fzf --prompt="Select repository: "
+  )
+
+  [ -z "$selected" ] && exit 0
+
+  "$SCRIPTS_DIR/tmux-new-session.sh" $PROJECTS_DIR/$selected
+
+}
+
+# :command.function
+dot_tmux_create_command() {
+
+  # src/tmux_create_command.sh
+  #!/bin/bash
+
+  DIR="$1"
+
+  echo "Creating new tmux session for directory: $DIR"
+
+  SESSION_NAME=$(basename "$DIR")
+
+  # replace dots with underline
+
+  SESSION_NAME=${SESSION_NAME//./_}
+
+  # create session detached
+  tmux new-session -d -s "$SESSION_NAME" -c "$DIR"
+
+  # rename the first window to "code"
+  tmux rename-window -t "$SESSION_NAME:0" "code"
+
+  # open nvim in the first window
+  tmux send-keys -t "$SESSION_NAME:0" "nvim" C-m
+
+  # create a new window for ai tools
+  # tmux new-window -t "$SESSION_NAME" -n "ai" -c "$DIR"
+
+  # open copilot chat in the ai window
+  # tmux send-keys -t "$SESSION_NAME:1" "copilot" C-m
+
+  # create a new window for running the code
+  tmux new-window -t "$SESSION_NAME" -n "run" -c "$DIR"
+
+  # select the first window
+  tmux select-window -t "$SESSION_NAME:0"
+
+  # tmux attach -t "$SESSION_NAME"
+
+  if [ "$SWITCH_CLIENT" = "1" ]; then
+      tmux switch-client -t "$SESSION_NAME"
+  else
+      tmux attach-session -t "$SESSION_NAME"
+  fi
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   local key
@@ -239,6 +379,13 @@ parse_requirements() {
       action="waybar"
       shift
       dot_waybar_parse_requirements "$@"
+      shift $#
+      ;;
+
+    tmux)
+      action="tmux"
+      shift
+      dot_tmux_parse_requirements "$@"
       shift $#
       ;;
 
@@ -449,6 +596,177 @@ dot_waybar_watch_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+dot_tmux_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        dot_tmux_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    project)
+      action="project"
+      shift
+      dot_tmux_project_parse_requirements "$@"
+      shift $#
+      ;;
+
+    create)
+      action="create"
+      shift
+      dot_tmux_create_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      dot_tmux_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+dot_tmux_project_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        dot_tmux_project_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tmux project"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+dot_tmux_create_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        dot_tmux_create_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tmux create"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   declare -g version="0.1.0"
@@ -472,6 +790,9 @@ run() {
     "waybar") dot_waybar_command ;;
     "waybar reload") dot_waybar_reload_command ;;
     "waybar watch") dot_waybar_watch_command ;;
+    "tmux") dot_tmux_command ;;
+    "tmux project") dot_tmux_project_command ;;
+    "tmux create") dot_tmux_create_command ;;
   esac
 }
 
