refactor: reorganize hypr commands

diff --git a/hyprland/hypr b/hyprland/hypr
--- a/hyprland/hypr
+++ b/hyprland/hypr
@@ -225,6 +225,75 @@ inspect_args() {
   fi
 }
 
+# :command.user_lib
+# commands/../lib/mod.sh
+is_mod_active(){
+    local mod=$1
+    [[ "$mod" != *.lua ]] && mod="$mod.lua"
+
+    local target="$HOME/.config/hypr/active/$mod"
+
+    [[ -L "$target" ]]
+}
+
+mod_exists(){
+    local mod=$1
+    [[ "$mod" != *.lua ]] && mod="$mod.lua"
+
+    local original="$HOME/.config/hypr/modifiers/$mod"
+
+    [[ -f "$original" ]]
+}
+
+# return [error, success]
+activate_mod(){
+    error=""
+    local mod=$1
+
+    [[ "$mod" != *.lua ]] && mod="$mod.lua"
+
+    if ! mod_exists "$mod"; then
+        error="$mod does not exist..."
+        return 1
+    fi
+
+    local original="$HOME/.config/hypr/modifiers/$mod"
+    local target="$HOME/.config/hypr/active/$mod"
+
+    if [ -L "$target" ]; then
+        error="$mod already active..."
+        return 1
+    fi
+
+    if [ ! -f "$original" ]; then
+        error="$mod does not exist..."
+        return 1
+    fi
+
+    ln -s $original $target
+}
+
+deactivate_mod(){
+    error=""
+    local mod=$1
+
+    [[ "$mod" != *.lua ]] && mod="$mod.lua"
+
+    if ! mod_exists "$mod"; then
+        error="$mod does not exist..."
+        return 1
+    fi
+
+    local target="$HOME/.config/hypr/active/$mod"
+
+    if [ ! -L "$target" ]; then
+        error="$mod not active..."
+        return 1
+    fi
+
+    rm $target
+}
+
 # :command.command_functions
 # :command.function
 hypr_list_command() {
@@ -258,24 +327,17 @@ hypr_activate_command() {
   fi
 
   for mod in "${modifiers[@]}"; do
-      # add lua extension if not present
-      [[ "$mod" != *.lua ]] && mod="$mod.lua"
-      original="$HOME/.config/hypr/modifiers/$mod"
-      target="$HOME/.config/hypr/active/${mod%.*}.lua"
 
-      if [ -f "$target" ]; then
-          echo "$mod alrady active..."
+      if is_mod_active "$mod"; then
+          echo "Modifier '$mod' is already active."
           continue
       fi
 
-      if [ ! -f "$original" ]; then
-          echo "$mod not found in modifiers..."
-          continue
+      if activate_mod "$mod"; then
+          echo "Modifier '$mod' activated successfully."
+      else
+          echo "Failed to activate modifier '$mod': $error"
       fi
-
-      ln -s $original $target
-
-      echo "activated: $original -> $target"
 
   done
 
@@ -294,18 +356,12 @@ hypr_deactivate_command() {
   fi
 
   for mod in "${modifiers[@]}"; do
-      # add lua extension if not present
-      [[ "$mod" != *.lua ]] && mod="$mod.lua"
-      target="$HOME/.config/hypr/active/${mod%.*}.lua"
 
-      if [ ! -f "$target" ]; then
-          echo "$mod not active..."
-          continue
+      if deactivate_mod "$mod"; then
+          echo "Modifier '$mod' deactivated successfully."
+      else
+          echo "Failed to deactivate modifier '$mod': $error"
       fi
-
-      rm "$target"
-
-      echo "deactivated: $original -> $target"
   done
 
 }
@@ -323,27 +379,11 @@ hypr_toggle_command() {
   fi
 
   for mod in "${modifiers[@]}"; do
-      # add lua extension if not present
-      [[ "$mod" != *.lua ]] && mod="$mod.lua"
-
-      original="$HOME/.config/hypr/modifiers/$mod"
-      target="$HOME/.config/hypr/active/${mod%.*}"
-
-      if [ -f "$target" ]; then
-          rm "$target"
-          echo "$mod deactivated..."
-          continue
+      if is_mod_active "$mod"; then
+          hypr_deactivate_command "$mod"
+      else
+          hypr_activate_command "$mod"
       fi
-
-      if [ ! -f "$original" ]; then
-          echo "$mod not found in modifiers..."
-          continue
-      fi
-
-      ln -s $original $target
-
-      echo "activated: $original -> $target"
-
   done
 
 }
