feat: vicinae command in hyprland

diff --git a/hyprland/hypr b/hyprland/hypr
--- a/hyprland/hypr
+++ b/hyprland/hypr
@@ -30,6 +30,7 @@ hypr_usage() {
   printf "  %s   activate hyprland modifier\n" "activate  "
   printf "  %s   deactivate hyprland modifier\n" "deactivate"
   printf "  %s   toggle hyprland modifier\n" "toggle    "
+  printf "  %s   generate viccinae scripts for hyprland modifiers\n" "vicinae   "
   echo
 
   # :command.long_usage
@@ -155,6 +156,28 @@ hypr_toggle_usage() {
     # :argument.usage
     printf "  %s\n" "MODIFIER..."
     printf "    modifier or list of modifiers\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+hypr_vicinae_usage() {
+  printf "hypr vicinae - generate viccinae scripts for hyprland modifiers\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  hypr vicinae\n"
+  printf "  hypr vicinae --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -388,6 +411,67 @@ hypr_toggle_command() {
 
 }
 
+# :command.function
+hypr_vicinae_command() {
+
+  # commands/vicinae_command.sh
+  all=(~/.config/hypr/modifiers/*)
+  dir="$HOME/.local/share/vicinae/scripts"
+  cli="$DOTFILES_DIR/hyprland/hypr"
+
+  for modifier in "${all[@]}"; do
+      base=$(basename "$modifier")
+      name="${base%.lua}"
+
+      activate_out="$dir/hypr_$name.sh"
+
+      touch "$activate_out"
+      chmod +x "$activate_out"
+
+      echo '#!/usr/bin/env bash' > "$activate_out"
+      echo "# @vicinae.schemaVersion 1" >> "$activate_out"
+      echo "# @vicinae.title [hypr] activate $name" >> "$activate_out"
+      echo "# @vicinae.mode silent" >> "$activate_out"
+      echo "# @vicinae.icon $HOME/.local/share/icons/hicolor/scalable/apps/hyprland.svg" >> "$activate_out"
+      echo >> "$activate_out"
+      echo "exec $cli toggle $name" >> "$activate_out"
+
+      echo "$activate_out created"
+
+      deactivate_out="$dir/hypr_deactivate_$name.sh"
+
+      touch "$deactivate_out"
+      chmod +x "$deactivate_out"
+
+      echo '#!/usr/bin/env bash' > "$deactivate_out"
+      echo "# @vicinae.schemaVersion 1" >> "$deactivate_out"
+      echo "# @vicinae.title [hypr] deactivate $name" >> "$deactivate_out"
+      echo "# @vicinae.mode silent" >> "$deactivate_out"
+      echo "# @vicinae.icon $HOME/.local/share/icons/hicolor/scalable/apps/hyprland.svg" >> "$deactivate_out"
+      echo >> "$deactivate_out"
+      echo "exec $cli deactivate $name" >> "$deactivate_out"
+
+      echo "$deactivate_out created"
+
+      toggle_out="$dir/hypr_toggle_$name.sh"
+
+      touch "$toggle_out"
+      chmod +x "$toggle_out"
+
+      echo '#!/usr/bin/env bash' > "$toggle_out"
+      echo "# @vicinae.schemaVersion 1" >> "$toggle_out"
+      echo "# @vicinae.title [hypr] toggle $name" >> "$toggle_out"
+      echo "# @vicinae.mode silent" >> "$toggle_out"
+      echo "# @vicinae.icon $HOME/.local/share/icons/hicolor/scalable/apps/hyprland.svg" >> "$toggle_out"
+      echo >> "$toggle_out"
+      echo "exec $cli toggle $name" >> "$toggle_out"
+
+      echo "$toggle_out created"
+
+  done
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   local key
@@ -445,6 +529,13 @@ parse_requirements() {
       action="toggle"
       shift
       hypr_toggle_parse_requirements "$@"
+      shift $#
+      ;;
+
+    vicinae)
+      action="vicinae"
+      shift
+      hypr_vicinae_parse_requirements "$@"
       shift $#
       ;;
 
@@ -720,6 +811,53 @@ hypr_toggle_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+hypr_vicinae_parse_requirements() {
+  local key
+
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        hypr_vicinae_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="vicinae"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   declare -g version="0.1.0"
@@ -745,6 +883,7 @@ run() {
     "activate") hypr_activate_command ;;
     "deactivate") hypr_deactivate_command ;;
     "toggle") hypr_toggle_command ;;
+    "vicinae") hypr_vicinae_command ;;
   esac
 }
 
